# Generated by Django 4.0.6 on 2022-07-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=5)),
                ('ship_date', models.DateField()),
                ('location_code', models.CharField(max_length=10)),
                ('del_date', models.DateField()),
                ('ship_type', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('order_no', models.CharField(max_length=20)),
                ('final_des', models.CharField(max_length=50)),
            ],
        ),
    ]
